services:
  - type: web
    name: django-ai-video
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings